services:
  prefect-server:
    image: prefecthq/prefect:3.4.14.dev3-python3.12
    container_name: prefect-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4200:4200"
    volumes:
      - prefect:/root/prefect
    command: prefect server start --host 0.0.0.0
    networks:
      - infra_default

volumes:
  prefect:

networks:
  infra_default:
    driver: bridge
